<?php
/**
 * @file
 * esdportal_str.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function esdportal_str_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'revision_id' => 3823,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Previously visited, pending response',
    'description' => '<br>
',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '090f8a6f-4610-40c2-80cd-81d6346aac7e',
    'vocabulary_machine_name' => 'site_visit_status',
  );
  $terms[] = array(
    'revision_id' => 3824,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'New, pending ESD month choice',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '16806273-1901-47ed-a11e-09a285a1bfe0',
    'vocabulary_machine_name' => 'site_visit_status',
  );
  $terms[] = array(
    'revision_id' => 3825,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Early childhood',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '22af93a5-974b-4f54-945a-5822a761484a',
    'vocabulary_machine_name' => 'school_type',
  );
  $terms[] = array(
    'revision_id' => 3826,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Opening soon',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '29493e55-d02f-4f9a-9eea-e00e7f817859',
    'vocabulary_machine_name' => 'school_status',
  );
  $terms[] = array(
    'revision_id' => 3827,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Not participating',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '327e8753-3870-4266-9783-84730c69885a',
    'vocabulary_machine_name' => 'site_visit_status',
  );
  $terms[] = array(
    'revision_id' => 3828,
    'log' => '',
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'HS',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5380e4dd-27fb-453b-80cd-49d48c6297b2',
    'vocabulary_machine_name' => 'school_type',
  );
  $terms[] = array(
    'revision_id' => 3829,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Mature',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5b609c8f-ada6-4e3b-abff-c5d237191b0b',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  $terms[] = array(
    'revision_id' => 3830,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Opt out',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5ce16c82-da65-422b-b412-163f98f0567a',
    'vocabulary_machine_name' => 'site_visit_status',
  );
  $terms[] = array(
    'revision_id' => 3831,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Mature',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '60bcb3e0-9427-4786-92ca-7432957eb745',
    'vocabulary_machine_name' => 'site_visit_status',
  );
  $terms[] = array(
    'revision_id' => 3832,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Open',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '62bb0923-69b7-4773-8752-0c6501ded9b5',
    'vocabulary_machine_name' => 'school_status',
  );
  $terms[] = array(
    'revision_id' => 3833,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Closed',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '68bd424f-119e-4a96-b508-b12fe7401044',
    'vocabulary_machine_name' => 'school_status',
  );
  $terms[] = array(
    'revision_id' => 3834,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Participating',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '8b922803-140b-420f-88a0-59719021288c',
    'vocabulary_machine_name' => 'site_visit_status',
  );
  $terms[] = array(
    'revision_id' => 3835,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'N/A',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '97393804-375a-4cbe-acb5-e8101fa3cd06',
    'vocabulary_machine_name' => 'site_visit_status',
  );
  $terms[] = array(
    'revision_id' => 3836,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'New',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a7043d6f-0819-42b0-a6d0-9589f63da815',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  $terms[] = array(
    'revision_id' => 3837,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Participating, pending date selection',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ab6ce65d-f88b-4241-881c-054e472bd043',
    'vocabulary_machine_name' => 'site_visit_status',
  );
  $terms[] = array(
    'revision_id' => 3838,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Revisit',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'afbc2c4d-7d86-4a73-a9e6-9204f341f32c',
    'vocabulary_machine_name' => 'site_visit_status',
  );
  $terms[] = array(
    'revision_id' => 3839,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Suburban',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'bca6bbce-bcf2-41e4-9941-bdac3d841063',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  $terms[] = array(
    'revision_id' => 3840,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Turnaround',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e2966d79-d2a5-41fe-ac49-92accbf83b70',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  $terms[] = array(
    'revision_id' => 3841,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'K8',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e4ade9de-bd69-4756-9360-2dec5260dfd2',
    'vocabulary_machine_name' => 'school_type',
  );
  $terms[] = array(
    'revision_id' => 3842,
    'log' => NULL,
    'timestamp' => 1394300232,
    'uid' => 0,
    'name' => 'Specialty',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ee5652ea-6e5a-4485-a46b-dac8ca3ff695',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  return $terms;
}
