<?php
/**
 * @file
 * esdportal_str.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function esdportal_str_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1472,
  'title' => 'Welcome',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '78f8628d-c5a7-44de-a29f-c55c68344405',
  'type' => 'page',
  'language' => 'und',
  'created' => 1375367357,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '04dd5a29-1017-4560-9c6c-806edecf1e95',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'We are working to make your participation in future years of the annual School Quality Review more seamless. This will include providing more timely information about the School Quality Review, and giving you a space to update your school information and to access your school’s site visit and survey reports--without having to fill out new forms and surveys every year.

And to make sure that parents will be receiving the best information about your schools, we have set you up as authors of your own school profiles (no this isn’t Facebook) and appreciate you taking the time to fill them out by logging in on the left and editing your profile.

This information will be tied directly to the updated online and print scorecards at the end of the summer.',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>We are working to make your participation in future years of the annual School Quality Review more seamless. This will include providing more timely information about the School Quality Review, and giving you a space to update your school information and to access your school’s site visit and survey reports--without having to fill out new forms and surveys every year.</p>
<p>And to make sure that parents will be receiving the best information about your schools, we have set you up as authors of your own school profiles (no this isn’t Facebook) and appreciate you taking the time to fill them out by logging in on the left and editing your profile.</p>
<p>This information will be tied directly to the updated online and print scorecards at the end of the summer.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'name' => 'michael@theworkdept.com',
  'picture' => 0,
  'data' => 'a:3:{s:7:"contact";i:1;s:7:"overlay";i:1;s:17:"mimemail_textonly";i:0;}',
  'date' => '2013-08-01 10:29:17 -0400',
);
  return $nodes;
}
