<?php
/**
 * @file
 * esdportal_str.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function esdportal_str_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'revision_id' => 636,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'Early childhood',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '22af93a5-974b-4f54-945a-5822a761484a',
    'vocabulary_machine_name' => 'school_type',
  );
  $terms[] = array(
    'revision_id' => 637,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'Opening soon',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '29493e55-d02f-4f9a-9eea-e00e7f817859',
    'vocabulary_machine_name' => 'school_status',
  );
  $terms[] = array(
    'revision_id' => 638,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'High school',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5380e4dd-27fb-453b-80cd-49d48c6297b2',
    'vocabulary_machine_name' => 'school_type',
  );
  $terms[] = array(
    'revision_id' => 639,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'Mature',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '5b609c8f-ada6-4e3b-abff-c5d237191b0b',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  $terms[] = array(
    'revision_id' => 640,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'Open',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '62bb0923-69b7-4773-8752-0c6501ded9b5',
    'vocabulary_machine_name' => 'school_status',
  );
  $terms[] = array(
    'revision_id' => 641,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'Closed',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => '68bd424f-119e-4a96-b508-b12fe7401044',
    'vocabulary_machine_name' => 'school_status',
  );
  $terms[] = array(
    'revision_id' => 642,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'New',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'a7043d6f-0819-42b0-a6d0-9589f63da815',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  $terms[] = array(
    'revision_id' => 643,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'Suburban',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'bca6bbce-bcf2-41e4-9941-bdac3d841063',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  $terms[] = array(
    'revision_id' => 644,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'Turnaround',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e2966d79-d2a5-41fe-ac49-92accbf83b70',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  $terms[] = array(
    'revision_id' => 645,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'K8',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'e4ade9de-bd69-4756-9360-2dec5260dfd2',
    'vocabulary_machine_name' => 'school_type',
  );
  $terms[] = array(
    'revision_id' => 646,
    'log' => NULL,
    'timestamp' => 1375286715,
    'uid' => 0,
    'name' => 'Specialty',
    'description' => '',
    'format' => 'full_html',
    'weight' => 0,
    'uuid' => 'ee5652ea-6e5a-4485-a46b-dac8ca3ff695',
    'vocabulary_machine_name' => 'school_scorecard_status',
  );
  return $terms;
}
