<?php
/**
 * @file
 * Code for the esdportal_str feature.
 */

include_once 'esdportal_str.features.inc';

/**
 * Implements hook_entity_info_alter().
 *
 * Add some view modes
 */
function esdportal_str_entity_info_alter(&$entity_info) {
  $entity_info['taxonomy_term']['view modes']['aside'] = array(
    'label' => t('Aside'),
    'custom settings' => FALSE,
  );
  $entity_info['node']['view modes']['sitevisitask'] = array(
    'label' => t('Site visit ask'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_preprocess_taxonomy_term().
 *
 * Add template hints for the added view modes
 */
function esdportal_str_preprocess_taxonomy_term(&$vars) {
  if($vars['view_mode'] == 'aside') {
    $vars['theme_hook_suggestions'][] = 'taxonomy_term__' . $vars['type'] . '__aside';
  }
}

/**
 * Implements hook_preprocess_node().
 *
 * Add template hints for the added view modes
 */
function esdportal_str_preprocess_node(&$vars) {
  if($vars['view_mode'] == 'sitevisitask') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__sitevisitask';
  }
}

/**
 * Implements hook_permission().
 *
 * Define permission to allow editing field_school and field_site_visit_status
 * term ref.
 */
function esdportal_str_permission() {
  return array(
    'view own field_school' => array('title' => t('View own field_school')),
    'edit own field_school' => array('title' => t('Edit own field_school')),
    'view any field_school' => array('title' => t('View any field_school')),
    'edit any field_school' => array('title' => t('Edit any field_school')),
    'view own field_site_visit_status' => array('title' => t('View own field_site_visit_status')),
    'edit own field_site_visit_status' => array('title' => t('Edit own field_site_visit_status')),
    'view any field_site_visit_status' => array('title' => t('View any field_site_visit_status')),
    'edit any field_site_visit_status' => array('title' => t('Edit any field_site_visit_status')),
  );
}

/**
 * Implements hook_field_access().
 *
 * Only allow users with granted permission, or theadministrator or logistics
 * coordinator roles, to update field_school taxnonomy reference.
 *
 * Only allow users with granted permission, or theadministrator or logistics
 * coordinator roles, to update field_site_visit_status taxnonomy reference.
 *
 * (follows field_permission_example module)
 */
function esdportal_str_field_access($op, $field, $entity_type, $entity, $account) {
  if ($field['field_name'] == 'field_school') {
    // allow superusers no matter whoziewhatsit
    if (user_access('bypass node access') || user_access('administer content types')) {
      return TRUE;
    }
    $context = 'any';
    if ($entity_type == 'node' && $entity && $entity->uid == $account->uid) {
      $context = 'own';
    }
    $perm = $op . ' ' . $context . ' field_school';
    $access = user_access($perm, $account);
    return $access;
  }
  if ($field['field_name'] == 'field_site_visit_status') {
    // allow superusers no matter whoziewhatsit
    if (user_access('bypass node access') || user_access('administer content types')) {
      return TRUE;
    }
    $context = 'any';
    if ($entity_type == 'node' && $entity && $entity->uid == $account->uid) {
      $context = 'own';
    }
    $perm = $op . ' ' . $context . ' field_site_visit_status';
    $access = user_access($perm, $account);
    return $access;
  }
  return TRUE;
}

/**
 * Feedback form, for use in footer.
 */
function esdportal_str_form() {
  $form['intro'] = array(
    '#markup' => t('Please provide us with any feedback or ideas you have about this site for us to continue improving it for you.'),
  );
  $form['comments'] = array(
    '#type' => 'textarea',
    '#rows' => 4,
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Implements hook_form_submit().
 */
function esdportal_str_form_submit($form, &$form_state) {
  global $user;

  $vals = $form_state['values'];

  $module = 'esdportal_str';
  $key = 'feedback';
  $from = variable_get('site_mail', 'eanderson@excellentschoolsdetroit.org');

  $message = drupal_mail($module, $key, $to, language_default(), $vals, $from, FALSE);
  $message['subject'] = t('Portal feedback from user @username', array('@username' => $user->name));
  $message['body'] = t('@name wrote:', array('@name' => $user->name)) . "\n\n" . $vals['comments'];
  $message['body'] .= "\n\n--\n" . t('Submitted by user @user from @url', array('@user' => $user->name, '@url' => $_SERVER['REQUEST_URI']));

  $system = drupal_mail_system($module, $key);

  $message['result'] = $system->mail($message);


  if ($message['result'] == TRUE) {
    drupal_set_message(t('Thank you for providing feedback.'));
  }
  else {
    drupal_set_message(t('There was a problem sending your feedback.'), 'error');
  }
}

/**
 * Implements hook_block_info().
 */
function esdportal_str_block_info() {
  return array(
    'feedback' => array(
      'info' => 'Feedback form',
      'cache' => DRUPAL_CACHE_PER_ROLE,
    ),
  );
}

/**
 * Implements hook_block_view().
 *
 * Feedback form block
 */
function esdportal_str_block_view($delta = '') {
  switch ($delta) {
    case 'feedback':
    default:
      $block['subject'] = t('Feedback');
      $block['content'] = drupal_get_form('esdportal_str_form');
    break;
  }
  return $block;
}

/**
 * Implements hook_views_pre_build().
 *
 * Alter data_ui views field handlers to output NULLs as empty rather than 0.
 */
function esdportal_str_views_pre_build(&$view) {
  /*
  if ($view->export_module = 'data_ui') {
    foreach ($view->field as $handler) {
      $handler->options['empty_zero'] = FALSE;
      $handler->options['hide_empty'] = TRUE;
    }
  }
  */
}
